apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
<<<<<<< HEAD
        image: hanjuhn/backend:1
=======
        image: hanjuhn/backend:1
>>>>>>> f1e6066 (add version file + reset image tags)
        env:
        - name: BADWORD_FN
          value: badword-filter
        ports:
        - containerPort: 8000
